### ISSUE TITLE
freesitemgr update site fails when another site cannot be found

### ISSUE THREAD

**Issue by debbiedub** [freenet/pyFreenet#35]
When I do `freesitemgr update site` and there is another site whose directory is not availables, I get the following error message and the command fails:
```$ freesitemgr update Icicle
Traceback (most recent call last):
  File "/usr/local/bin/freesitemgr", line 563, in <module>
    main()
  File "/usr/local/bin/freesitemgr", line 444, in main
    sitemgr = SiteMgr(*args, **opts)
  File "/usr/local/lib/python3.10/site-packages/fcp3/sitemgr.py", line 104, in __init__
    self.load()
  File "/usr/local/lib/python3.10/site-packages/fcp3/sitemgr.py", line 166, in load
    site = SiteState(
  File "/usr/local/lib/python3.10/site-packages/fcp3/sitemgr.py", line 503, in __init__
    raise Exception("Site %s, directory %s nonexistent" % (
Exception: Site t3, directory /home/debbiedub/test/t3 nonexistent
```
The problem is in pyFreenet-0.5.8 (freesitemgr 0.3.4).

**Comment by Thynix** [comment]
Is my understanding correct that the behavior you would expect is that it only matter whether the site you've specified doesn't exist?
